# Exported from Render on 2026-07-10T17:45:01Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Promotix
      runtime: node
      repo: https://github.com/alokrk04/Promotix
      plan: free
      envVars:
      - key: SESSION_SECRET
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: PORT
        sync: false
      - key: .env
        sync: false
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: 'uvicorn main:app --host 0.0.0.0 --port 10000 '
      autoDeployTrigger: commit
      rootDir: backend
